services:
  - type: web
    name: bot-whatsapp
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "false"
